// src/LanguageContext.jsx
import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    appTitle: "Soroban For School",
    startQuiz: "Start Quiz",
    settings: "Settings",
    backHome: "Home",
    chapter: "Chapter",
    level: "Book", // Changed from Level
    questions: "Questions",
    speed: "Speed",
    flash: "Flash Tokens",
    dictation: "Voice", 
    timer: "Timer (min)",
    mute: "Mute",
    save: "Save",
    cancel: "Cancel",
    results: "Results",
    perfect: "Perfect! 🎉",
    timesUp: "Time's Up!",
    score: "You scored",
    tryAgain: "Try Again",
    send: "Send",
    loading: "Loading...",
    loginTitle: "Sign In",
    username: "Username",
    password: "Password",
    signingIn: "Signing in...",
    errorFill: "Fill all fields",
    logout: "Log Out",
    voiceVol: "Voice Volume",
    sfxVol: "SFX Volume",
    watchLesson: "Watch Lesson",
    slideshow: "Gallery",
    videoError: "Video not available",
    exercise: "Exercise",
    next: "Next",
    nickname: "Nickname",
    saveNickname: "Save nickname",
    fontSize: "Font Size",
    equals: "Equals",
    plus: "Plus",
    minus: "Minus",
    practiceGames: "Practice Games",
    flashcardPractice: "Flashcard Practice",
    nadaCalendar: "Nada Calendar",
    // Calendar Game
    weekdayShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    weekdayFull: ["SUNDAY", "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY"],
    yearFormat: "Year Format",
    normalYear: "A.D. (2025)",
    thaiYear: "B.E. (2568)",
    spin: "SPIN!",
    reveal: "REVEAL",
    playAgain: "PLAY AGAIN",
    getReady: "GET READY",
    complete: "COMPLETE!",
    day: "DAY",
    month: "MONTH",
    year: "YEAR",
    rotateDevice: "ROTATE DEVICE",
    rotateHint: "Please use landscape for this game.",
    rotateCta: "Rotate to continue",
    tapToStart: "TAP TO START",
    gameSetup: "GAME SETUP",
    winningDate: "Winning Date",
    // Flashcard Game
    speedSec: "Speed (ms)",
    numbersPerSet: "Numbers/Set",
    rounds: "Rounds",
    mode: "Mode",
    modePractice: "Practice",
    modeCompetition: "Competition",
    startGame: "START GAME",
    nextSet: "NEXT",
    submit: "SUBMIT",
    finish: "FINISH",
    summary: "RESULTS",
    correct: "CORRECT!",
    wrong: "WRONG!",
    answerWas: "Answer:",
    mainMenu: "BACK",
    voice: "Voice"
  },
  th: {
    appTitle: "Soroban For School",
    startQuiz: "เริ่มทำแบบทดสอบ",
    settings: "ตั้งค่า",
    backHome: "หน้าหลัก",
    chapter: "บทที่",
    level: "เล่ม", // Changed from ระดับ
    questions: "จำนวนข้อ",
    speed: "ความเร็ว (วิ)",
    flash: "แฟลชตัวเลข",
    dictation: "เสียงอ่าน",
    timer: "เวลา (นาที)",
    mute: "ปิดเสียง",
    save: "บันทึก",
    cancel: "ยกเลิก",
    results: "ผลลัพธ์",
    perfect: "ยอดเยี่ยม! 🎉",
    timesUp: "หมดเวลา!",
    score: "คะแนนของคุณ",
    tryAgain: "ลองอีกครั้ง",
    send: "ส่งคำตอบ",
    loading: "กำลังโหลด...",
    loginTitle: "เข้าสู่ระบบ",
    username: "ชื่อผู้ใช้",
    password: "รหัสผ่าน",
    signingIn: "กำลังเข้าสู่ระบบ...",
    errorFill: "กรุณากรอกข้อมูลให้ครบ",
    logout: "ออกจากระบบ",
    voiceVol: "ความเสียงอ่าน",
    sfxVol: "เสียงเอฟเฟกต์",
    watchLesson: "ดูบทเรียน",
    slideshow: "อัลบั้มภาพ",
    videoError: "ไม่พบวิดีโอ",
    exercise: "แบบฝึกหัด",
    next: "ถัดไป",
    nickname: "ชื่อเล่น",
    saveNickname: "บันทึกชื่อเล่น",
    fontSize: "ขนาดตัวอักษร",
    equals: "เท่ากับ",
    plus: "บวก",
    minus: "ลบ",
    practiceGames: "เกมฝึกหัด",
    flashcardPractice: "ฝึกแฟลชการ์ด",
    nadaCalendar: "ปฏิทินนาดา",
    // Calendar Game
    weekdayShort: ["อา", "จ", "อ", "พ", "พฤ", "ศ", "ส"],
    weekdayFull: ["วันอาทิตย์", "วันจันทร์", "วันอังคาร", "วันพุธ", "วันพฤหัสบดี", "วันศุกร์", "วันเสาร์"],
    yearFormat: "รูปแบบปี",
    normalYear: "ค.ศ.",
    thaiYear: "พ.ศ.",
    spin: "หมุน!",
    reveal: "เฉลย",
    playAgain: "เล่นอีกครั้ง",
    getReady: "เตรียมตัว",
    complete: "เรียบร้อย!",
    day: "วัน",
    month: "เดือน",
    year: "ปี",
    rotateDevice: "หมุนหน้าจอ",
    rotateHint: "กรุณาหมุนหน้าจอเป็นแนวนอนเพื่อเล่นเกมนี้",
    rotateCta: "หมุนหน้าจอเพื่อไปต่อ",
    tapToStart: "แตะเพื่อเริ่ม",
    gameSetup: "ตั้งค่าเกม",
    winningDate: "วันที่ชนะ",
    // Flashcard Game
    speedSec: "ความเร็ว (ms)",
    numbersPerSet: "ตัวเลข/ชุด",
    rounds: "จำนวนรอบ",
    mode: "โหมด",
    modePractice: "ฝึกซ้อม",
    modeCompetition: "แข่งขัน",
    startGame: "เริ่มเกม",
    nextSet: "ถัดไป",
    submit: "ส่งคำตอบ",
    finish: "จบเกม",
    summary: "สรุปผล",
    correct: "ถูกต้อง!",
    wrong: "ผิด!",
    answerWas: "คำตอบ:",
    mainMenu: "กลับ",
    voice: "เสียงอ่าน"
  }
};

export const chapterTitlesTH = {
  1: [
    "ปัดเม็ดล่าง (Lower)",
    "ปัดเม็ดล่าง 2 หลัก (Lower 2 digit)",
    "ปัดเม็ดบน (Upper)",
    "ผสม ปัดเม็ดบนล่าง (Mix Lower Upper)",
    "ผสม ปัดเม็ดบนล่าง 2 หลัก (Mix Lower Upper 2 digit)",
    "คู่หู 5 (+4)",
    "คู่หู 5 (+3)",
    "คู่หู 5 (+2)",
    "คู่หู 5 (+1)",
    "คู่หู 5 (บวก)",
    "คู่หู 5 (-4)",
    "คู่หู 5 (-3)",
    "คู่หู 5 (-2)",
    "คู่หู 5 (-1)",
    "คู่หู 5 (ลบ)",
    "ผสม คู่หู 5 (Mix Five buddy)",
    "ผสม คู่หู 5 2 หลัก (Mix Five buddy 2 digit)"
  ],
  4: [
    "ปัดเม็ดบนล่าง (2 หลัก)",
    "คู่หู 5 (+4) (2 หลัก)",
    "คู่หู 5 (+3) (2 หลัก)",
    "คู่หู 5 (+2) (2 หลัก)",
    "คู่หู 5 (+1) (2 หลัก)",
    "คู่หู 5 (-4) (2 หลัก)",
    "คู่หู 5 (-3) (2 หลัก)",
    "คู่หู 5 (-2) (2 หลัก)",
    "คู่หู 5 (-1) (2 หลัก)",
    "คู่หู 10 (+9) (2 หลัก)",
    "คู่หู 10 (+8) (2 หลัก)",
    "คู่หู 10 (+7) (2 หลัก)",
    "คู่หู 10 (+6) (2 หลัก)",
    "คู่หู 10 (+5) (2 หลัก)",
    "คู่หู 10 (+4) (2 หลัก)",
    "คู่หู 10 (+3) (2 หลัก)",
    "คู่หู 10 (+2) (2 หลัก)",
    "คู่หู 10 (+1) (2 หลัก)",
    "คู่หู 10 (-9) (2 หลัก)",
    "คู่หู 10 (-8) (2 หลัก)",
    "คู่หู 10 (-7) (2 หลัก)",
    "คู่หู 10 (-6) (2 หลัก)",
    "คู่หู 10 (-5) (2 หลัก)",
    "คู่หู 10 (-4) (2 หลัก)",
    "คู่หู 10 (-3) (2 หลัก)",
    "คู่หู 10 (-2) (2 หลัก)",
    "คู่หู 10 (-1) (2 หลัก)",
    "คู่หู 5&10 (+9) (2 หลัก)",
    "คู่หู 5&10 (+8) (2 หลัก)",
    "คู่หู 5&10 (+7) (2 หลัก)",
    "คู่หู 5&10 (+6) (2 หลัก)",
    "คู่หู 5&10 (-9) (2 หลัก)",
    "คู่หู 5&10 (-8) (2 หลัก)",
    "คู่หู 5&10 (-7) (2 หลัก)",
    "คู่หู 5&10 (-6) (2 หลัก)"
  ]
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');

  const toggleLang = () => {
    setLang((prev) => (prev === 'en' ? 'th' : 'en'));
  };

  const t = translations[lang];

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}